apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-glados-thorstensauter-dev
  namespace: argocd
spec:
  secretName: argocd-glados-thorstensauter-dev-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "argocd.glados.thorstensauter.dev"
  dnsNames:
    - "argocd.glados.thorstensauter.dev"
