apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-key-vault
  namespace: external-secrets
spec:
  provider:
    azurekv:
      authSecretRef:
        clientId:
          name: azure-sp
          namespace: external-secrets
          key: ClientID
        clientSecret:
          name: azure-sp
          namespace: external-secrets
          key: ClientSecret
