apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: thorsten.sauter@gmail.com
    solvers:
      - dns01:
          cloudflare:
            email: thorsten.sauter@gmail.com
        selector:
          dnsZones:
            - "thorstensauter.dev"