apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-sso-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: oidc.azure.clientSecret
      remoteRef:
        key: argocd-sso-client-secret
