apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  labels:
    name: argo-cd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-cd
    helm:
      valueFiles:
        - ../values/argocd.yaml
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: v5.9.0
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
