apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    name: external-secrets
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: external-secrets
    helm:
      parameters:
        - name: installCRDs
          value: "true"
    repoURL: https://charts.external-secrets.io
    targetRevision: v0.6.1
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
