apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-key-vault
  namespace: external-secrets
spec:
  provider:
    azurekv:
      tenantId: "ffab38df-cddf-433f-859a-6cfa161a5ceb"
      vaultUrl: "https://k8sgladosdevwesteurope01.vault.azure.net"